id: P009221
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159417
  title: བོན་བཤད་པོ་ཏི་ཕྲ་མོ།
  author: ''
  volumes:
    710ec086fbb34c9eba8839f75affcd5d:
      image_group_id: I2PD19049
      title: ''
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
